### ISSUE TITLE
Path to packageName conversion not working under Windows

### ISSUE THREAD

**Issue by gwyn** [jochenseeber/gradle-wsimport-plugin#2]
The path to package name conversion in WsimportTask does not work under Microsoft Windows. It breaks because of a different file separator on this platform (backslash instead of forward slash). Simple fix:

``` groovy
def packageName = relativeSourceFile.parent.replace(File.separator, '.')
```

**Comment by jochenseeber** [comment]
The plugin was rewritten in Java, this should work now.
